namespace AutoUpdater.Tests;

internal static class TestData
{
    public static string ReleasesResponse => @"[
  {
    ""url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/177417338"",
    ""assets_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/177417338/assets"",
    ""upload_url"": ""https://uploads.github.com/repos/BobbyRachkov/InspectaQueue/releases/177417338/assets{?name,label}"",
    ""html_url"": ""https://github.com/BobbyRachkov/InspectaQueue/releases/tag/0.1.2.0"",
    ""id"": 177417338,
    ""author"": {
      ""login"": ""BobbyRachkov"",
      ""id"": 15618639,
      ""node_id"": ""MDQ6VXNlcjE1NjE4NjM5"",
      ""avatar_url"": ""https://avatars.githubusercontent.com/u/15618639?v=4"",
      ""gravatar_id"": """",
      ""url"": ""https://api.github.com/users/BobbyRachkov"",
      ""html_url"": ""https://github.com/BobbyRachkov"",
      ""followers_url"": ""https://api.github.com/users/BobbyRachkov/followers"",
      ""following_url"": ""https://api.github.com/users/BobbyRachkov/following{/other_user}"",
      ""gists_url"": ""https://api.github.com/users/BobbyRachkov/gists{/gist_id}"",
      ""starred_url"": ""https://api.github.com/users/BobbyRachkov/starred{/owner}{/repo}"",
      ""subscriptions_url"": ""https://api.github.com/users/BobbyRachkov/subscriptions"",
      ""organizations_url"": ""https://api.github.com/users/BobbyRachkov/orgs"",
      ""repos_url"": ""https://api.github.com/users/BobbyRachkov/repos"",
      ""events_url"": ""https://api.github.com/users/BobbyRachkov/events{/privacy}"",
      ""received_events_url"": ""https://api.github.com/users/BobbyRachkov/received_events"",
      ""type"": ""User"",
      ""site_admin"": false
    },
    ""node_id"": ""RE_kwDOMfMLwc4Kkyx6"",
    ""tag_name"": ""0.1.2.0"",
    ""target_commitish"": ""master"",
    ""name"": ""0.1.2.0"",
    ""draft"": false,
    ""prerelease"": false,
    ""created_at"": ""2024-09-28T11:44:08Z"",
    ""published_at"": ""2024-09-28T11:53:22Z"",
    ""assets"": [
      {
        ""url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/assets/195515995"",
        ""id"": 195515995,
        ""node_id"": ""RA_kwDOMfMLwc4Lp1Zb"",
        ""name"": ""InspectaQueue_0.1.2.0.zip"",
        ""label"": null,
        ""uploader"": {
          ""login"": ""BobbyRachkov"",
          ""id"": 15618639,
          ""node_id"": ""MDQ6VXNlcjE1NjE4NjM5"",
          ""avatar_url"": ""https://avatars.githubusercontent.com/u/15618639?v=4"",
          ""gravatar_id"": """",
          ""url"": ""https://api.github.com/users/BobbyRachkov"",
          ""html_url"": ""https://github.com/BobbyRachkov"",
          ""followers_url"": ""https://api.github.com/users/BobbyRachkov/followers"",
          ""following_url"": ""https://api.github.com/users/BobbyRachkov/following{/other_user}"",
          ""gists_url"": ""https://api.github.com/users/BobbyRachkov/gists{/gist_id}"",
          ""starred_url"": ""https://api.github.com/users/BobbyRachkov/starred{/owner}{/repo}"",
          ""subscriptions_url"": ""https://api.github.com/users/BobbyRachkov/subscriptions"",
          ""organizations_url"": ""https://api.github.com/users/BobbyRachkov/orgs"",
          ""repos_url"": ""https://api.github.com/users/BobbyRachkov/repos"",
          ""events_url"": ""https://api.github.com/users/BobbyRachkov/events{/privacy}"",
          ""received_events_url"": ""https://api.github.com/users/BobbyRachkov/received_events"",
          ""type"": ""User"",
          ""site_admin"": false
        },
        ""content_type"": ""application/x-zip-compressed"",
        ""state"": ""uploaded"",
        ""size"": 23327994,
        ""download_count"": 3,
        ""created_at"": ""2024-09-28T11:53:12Z"",
        ""updated_at"": ""2024-09-28T11:53:19Z"",
        ""browser_download_url"": ""https://github.com/BobbyRachkov/InspectaQueue/releases/download/0.1.2.0/InspectaQueue_0.1.2.0.zip""
      }
    ],
    ""tarball_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/tarball/0.1.2.0"",
    ""zipball_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/zipball/0.1.2.0"",
    ""body"": ""Change folder structure""
  },
  {
    ""url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/177416315"",
    ""assets_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/177416315/assets"",
    ""upload_url"": ""https://uploads.github.com/repos/BobbyRachkov/InspectaQueue/releases/177416315/assets{?name,label}"",
    ""html_url"": ""https://github.com/BobbyRachkov/InspectaQueue/releases/tag/0.1.1.0"",
    ""id"": 177416315,
    ""author"": {
      ""login"": ""BobbyRachkov"",
      ""id"": 15618639,
      ""node_id"": ""MDQ6VXNlcjE1NjE4NjM5"",
      ""avatar_url"": ""https://avatars.githubusercontent.com/u/15618639?v=4"",
      ""gravatar_id"": """",
      ""url"": ""https://api.github.com/users/BobbyRachkov"",
      ""html_url"": ""https://github.com/BobbyRachkov"",
      ""followers_url"": ""https://api.github.com/users/BobbyRachkov/followers"",
      ""following_url"": ""https://api.github.com/users/BobbyRachkov/following{/other_user}"",
      ""gists_url"": ""https://api.github.com/users/BobbyRachkov/gists{/gist_id}"",
      ""starred_url"": ""https://api.github.com/users/BobbyRachkov/starred{/owner}{/repo}"",
      ""subscriptions_url"": ""https://api.github.com/users/BobbyRachkov/subscriptions"",
      ""organizations_url"": ""https://api.github.com/users/BobbyRachkov/orgs"",
      ""repos_url"": ""https://api.github.com/users/BobbyRachkov/repos"",
      ""events_url"": ""https://api.github.com/users/BobbyRachkov/events{/privacy}"",
      ""received_events_url"": ""https://api.github.com/users/BobbyRachkov/received_events"",
      ""type"": ""User"",
      ""site_admin"": false
    },
    ""node_id"": ""RE_kwDOMfMLwc4Kkyh7"",
    ""tag_name"": ""0.1.1.0"",
    ""target_commitish"": ""master"",
    ""name"": ""0.1.1.0"",
    ""draft"": false,
    ""prerelease"": true,
    ""created_at"": ""2024-09-28T11:22:57Z"",
    ""published_at"": ""2024-09-28T11:26:09Z"",
    ""assets"": [
      {
        ""url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/assets/195514668"",
        ""id"": 195514668,
        ""node_id"": ""RA_kwDOMfMLwc4Lp1Es"",
        ""name"": ""InspectaQueue_0.1.1.0.zip"",
        ""label"": null,
        ""uploader"": {
          ""login"": ""BobbyRachkov"",
          ""id"": 15618639,
          ""node_id"": ""MDQ6VXNlcjE1NjE4NjM5"",
          ""avatar_url"": ""https://avatars.githubusercontent.com/u/15618639?v=4"",
          ""gravatar_id"": """",
          ""url"": ""https://api.github.com/users/BobbyRachkov"",
          ""html_url"": ""https://github.com/BobbyRachkov"",
          ""followers_url"": ""https://api.github.com/users/BobbyRachkov/followers"",
          ""following_url"": ""https://api.github.com/users/BobbyRachkov/following{/other_user}"",
          ""gists_url"": ""https://api.github.com/users/BobbyRachkov/gists{/gist_id}"",
          ""starred_url"": ""https://api.github.com/users/BobbyRachkov/starred{/owner}{/repo}"",
          ""subscriptions_url"": ""https://api.github.com/users/BobbyRachkov/subscriptions"",
          ""organizations_url"": ""https://api.github.com/users/BobbyRachkov/orgs"",
          ""repos_url"": ""https://api.github.com/users/BobbyRachkov/repos"",
          ""events_url"": ""https://api.github.com/users/BobbyRachkov/events{/privacy}"",
          ""received_events_url"": ""https://api.github.com/users/BobbyRachkov/received_events"",
          ""type"": ""User"",
          ""site_admin"": false
        },
        ""content_type"": ""application/x-zip-compressed"",
        ""state"": ""uploaded"",
        ""size"": 23327115,
        ""download_count"": 2,
        ""created_at"": ""2024-09-28T11:26:17Z"",
        ""updated_at"": ""2024-09-28T11:26:23Z"",
        ""browser_download_url"": ""https://github.com/BobbyRachkov/InspectaQueue/releases/download/0.1.1.0/InspectaQueue_0.1.1.0.zip""
      }
    ],
    ""tarball_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/tarball/0.1.1.0"",
    ""zipball_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/zipball/0.1.1.0"",
    ""body"": ""Install scripts added""
  },
  {
    ""url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/176243462"",
    ""assets_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/176243462/assets"",
    ""upload_url"": ""https://uploads.github.com/repos/BobbyRachkov/InspectaQueue/releases/176243462/assets{?name,label}"",
    ""html_url"": ""https://github.com/BobbyRachkov/InspectaQueue/releases/tag/0.1.0.0"",
    ""id"": 176243462,
    ""author"": {
      ""login"": ""BobbyRachkov"",
      ""id"": 15618639,
      ""node_id"": ""MDQ6VXNlcjE1NjE4NjM5"",
      ""avatar_url"": ""https://avatars.githubusercontent.com/u/15618639?v=4"",
      ""gravatar_id"": """",
      ""url"": ""https://api.github.com/users/BobbyRachkov"",
      ""html_url"": ""https://github.com/BobbyRachkov"",
      ""followers_url"": ""https://api.github.com/users/BobbyRachkov/followers"",
      ""following_url"": ""https://api.github.com/users/BobbyRachkov/following{/other_user}"",
      ""gists_url"": ""https://api.github.com/users/BobbyRachkov/gists{/gist_id}"",
      ""starred_url"": ""https://api.github.com/users/BobbyRachkov/starred{/owner}{/repo}"",
      ""subscriptions_url"": ""https://api.github.com/users/BobbyRachkov/subscriptions"",
      ""organizations_url"": ""https://api.github.com/users/BobbyRachkov/orgs"",
      ""repos_url"": ""https://api.github.com/users/BobbyRachkov/repos"",
      ""events_url"": ""https://api.github.com/users/BobbyRachkov/events{/privacy}"",
      ""received_events_url"": ""https://api.github.com/users/BobbyRachkov/received_events"",
      ""type"": ""User"",
      ""site_admin"": false
    },
    ""node_id"": ""RE_kwDOMfMLwc4KgUMG"",
    ""tag_name"": ""0.1.0.0"",
    ""target_commitish"": ""master"",
    ""name"": ""Alpha release 0.1.0.0"",
    ""draft"": false,
    ""prerelease"": false,
    ""created_at"": ""2024-09-21T17:50:16Z"",
    ""published_at"": ""2024-09-21T17:53:00Z"",
    ""assets"": [
      {
        ""url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/releases/assets/194042577"",
        ""id"": 194042577,
        ""node_id"": ""RA_kwDOMfMLwc4LkNrR"",
        ""name"": ""InspectaQueue_0.1.0.0.zip"",
        ""label"": null,
        ""uploader"": {
          ""login"": ""BobbyRachkov"",
          ""id"": 15618639,
          ""node_id"": ""MDQ6VXNlcjE1NjE4NjM5"",
          ""avatar_url"": ""https://avatars.githubusercontent.com/u/15618639?v=4"",
          ""gravatar_id"": """",
          ""url"": ""https://api.github.com/users/BobbyRachkov"",
          ""html_url"": ""https://github.com/BobbyRachkov"",
          ""followers_url"": ""https://api.github.com/users/BobbyRachkov/followers"",
          ""following_url"": ""https://api.github.com/users/BobbyRachkov/following{/other_user}"",
          ""gists_url"": ""https://api.github.com/users/BobbyRachkov/gists{/gist_id}"",
          ""starred_url"": ""https://api.github.com/users/BobbyRachkov/starred{/owner}{/repo}"",
          ""subscriptions_url"": ""https://api.github.com/users/BobbyRachkov/subscriptions"",
          ""organizations_url"": ""https://api.github.com/users/BobbyRachkov/orgs"",
          ""repos_url"": ""https://api.github.com/users/BobbyRachkov/repos"",
          ""events_url"": ""https://api.github.com/users/BobbyRachkov/events{/privacy}"",
          ""received_events_url"": ""https://api.github.com/users/BobbyRachkov/received_events"",
          ""type"": ""User"",
          ""site_admin"": false
        },
        ""content_type"": ""application/zip"",
        ""state"": ""uploaded"",
        ""size"": 23327551,
        ""download_count"": 35,
        ""created_at"": ""2024-09-21T17:51:18Z"",
        ""updated_at"": ""2024-09-21T17:51:34Z"",
        ""browser_download_url"": ""https://github.com/BobbyRachkov/InspectaQueue/releases/download/0.1.0.0/InspectaQueue_0.1.0.0.zip""
      }
    ],
    ""tarball_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/tarball/0.1.0.0"",
    ""zipball_url"": ""https://api.github.com/repos/BobbyRachkov/InspectaQueue/zipball/0.1.0.0"",
    ""body"": ""Alpha release with basic live read functionality without auto updater""
  }
]";

}